version: "3"

services:
  mysql1: &mysql
    container_name: master
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_USER: ${USER}
      MYSQL_PASSWORD: ${PASSWORD}
    volumes:
      - ./mysqlData1:/var/lib/mysql
  mysql2:
    <<: *mysql
    container_name: slave
    ports:
      - "3308:3306"
    volumes:
      - ./mysqlData2:/var/lib/mysql
