// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Video is the predicate function for video builders.
type Video func(*sql.Selector)
