// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package city

import (
	"example.com/basics/cmd/wire/event"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeCity(eventName string) (City, error) {
	message := event.NewMessage(eventName)
	greeter := event.NewGreeter(message)
	eventEvent, err := event.NewEvent(greeter)
	if err != nil {
		return City{}, err
	}
	city := NewCity(eventEvent)
	return city, nil
}

// wire.go:

var CitySet = wire.NewSet(NewCity, event.EventSet)
