// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package city

import (
	"example.com/basics/wire/event"
	"github.com/google/wire"
)

// Injectors from city_wire.go:

func InitializeCity(eventName string) (City, error) {
	message := event.NewMessage(eventName)
	greeter := event.NewGreeter(message)
	eventEvent, err := event.NewEvent(greeter)
	if err != nil {
		return City{}, err
	}
	city := NewCity(eventEvent)
	return city, nil
}

// Injectors from event_wire.go:

func InitializeEvent(phrase string) (event.Event, error) {
	message := event.NewMessage(phrase)
	greeter := event.NewGreeter(message)
	eventEvent, err := event.NewEvent(greeter)
	if err != nil {
		return event.Event{}, err
	}
	return eventEvent, nil
}

// city_wire.go:

var CitySet = wire.NewSet(NewCity, event.EventSet)

// event_wire.go:

var EventSet = wire.NewSet(event.EventSet)
