# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/helloworld.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'v1/helloworld.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1 import pong_pb2 as v1_dot_pong__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13v1/helloworld.proto\x12\x0eprotogen.v1.pb\x1a\x1bgoogle/protobuf/empty.proto\x1a\rv1/pong.proto\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x88\x01\n\x07Greeter\x12G\n\x08SayHello\x12\x1c.protogen.v1.pb.HelloRequest\x1a\x1d.protogen.v1.pb.HelloResponse\x12\x34\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x14.protogen.v1.pb.PongB\x10Z\x0eprotogen/v1;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.helloworld_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\016protogen/v1;pb'
  _globals['_HELLOREQUEST']._serialized_start=83
  _globals['_HELLOREQUEST']._serialized_end=111
  _globals['_HELLORESPONSE']._serialized_start=113
  _globals['_HELLORESPONSE']._serialized_end=145
  _globals['_GREETER']._serialized_start=148
  _globals['_GREETER']._serialized_end=284
# @@protoc_insertion_point(module_scope)
